name: Automerge

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          label: automerge
